### ISSUE TITLE
Can't work with Privileged Apps

### ISSUE THREAD

**Issue by kloben** [mozilla/inneractive#2]
Ads are not showing when you define your app as privileged in manifest.webapp.

Only shows the black blackground. It throws no errors in console.

**Comment by louisstow** [comment]
Does it work if the app is just packaged?

**Comment by trpn** [comment]
I can confirm this as well. 
Ad shows when app running from a web server and accessed by Firefox browser (windows and android).
Ad is a black box when app installed as a privileged app or when running from a web server and accessed by Chrome (windows).

**Comment by rickgbw** [comment]
Still not showing for privileged apps...
